basic/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('feed/',include('books.urls'))
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404="notfound.views.page_not_found_view"
handler500="notfound.views.handle_server_found"

books/urls.py
from django.urls import path
from .views import  (   
                        FeedBookView,
                        DetailView,
                        LikeView,
                        BookCreateView,
                        BookEditView,
                        BookDeleteView,
                        BookSearch,
                        UserSearch,
                        BookReviewEdit,
                        CommentDelete,
                        CommentDeletes,
                        BookDeleteMessage,
                        FriendReview,
                        BookTop,
                        favouritebook,
                        deletefavouritebook,
                        FavouriteBook
        
)


app_name='books'
urlpatterns=[
    path('',FeedBookView.as_view(),name='feed'),# wrote test
    path('bookserach/',BookSearch.as_view(),name='booksearch'),# wrote test
    path('usersearch/',UserSearch.as_view(),name="usersearch"),# wrote test
    path('bookTop/',BookTop.as_view(),name="Booktop"),
    path('mybookfavourite/',FavouriteBook.as_view(),name="bookfavourite"),
    path('friendreviw/',FriendReview.as_view(),name="friendreview"),
    path('<int:id>/',DetailView.as_view(),name='detail'),# wrote test
    path('like/<int:id>/',LikeView.as_view(),name="like"),# wrote test
    path('bookcreate/',BookCreateView.as_view(),name="bookcreate"),
    path('bookcreate/<int:id>/edit/',BookEditView.as_view(),name="bookedit"),
    path('bookdelete/<int:id>/messge/',BookDeleteMessage.as_view(),name="deletemessage"),# wrote test
    path('bookcreate/<int:id>/delete/',BookDeleteView.as_view(),name="bookdelete"),# wrote test
    path('<int:book_id>/comments/<int:comment_id>/edit/',BookReviewEdit.as_view(),name='commentedit'), # wrote test
    path('<int:book_id>/view/<int:comment_id>',CommentDelete.as_view(),name='commentdelete'),# wrote test
    path('<int:book_id>/delete/<int:comment_id>deletes/',CommentDeletes.as_view(),name='commentdeletes'),# wrote test
    path('favouritebook/<int:id>/',favouritebook.as_view(),name='favourite'),
    path('favouritebook/<int:id>/delete',deletefavouritebook.as_view(),name='deletelikebook'),

]

users/urls.py
from django.urls import path
from .views import ( RegisterUSer,
                     LoginUser,
                     LogoutView,
                     FriendChat,
                     FriendProfile,
                     Follow,
                     ChatView,
                     MyProfile,
                     Followers,
                     Following,
                     UpdateUser,
                     FeedFollow
                     )



app_name='users'
urlpatterns=[
    path('register/',RegisterUSer.as_view(),name='register'),#The test was written
    path('profile/',MyProfile.as_view(),name='userprofile'),#The test was written
    path('profile/updateuserprofile/',UpdateUser.as_view(),name='updateuser'),#The test was written
    path('',LoginUser.as_view(),name='login'),#The test was written
    path('logout/',LogoutView.as_view(),name='logout'),#The test was written
    path('friendchat/',FriendChat.as_view(),name="friendchat",),#The test was written
    path('users/<int:id>/',FriendProfile.as_view(),name="user_follow",),
    path('users/<int:id>/follow/',Follow.as_view(),name="follow",),#The test was written
    path('friendchat/<int:id>/chat/',ChatView.as_view(),name="chat",),#The test was written
    path('users/<int:id>/followers/',Followers.as_view(),name="followers",),#The test was written
    path('users/<int:id>/following/',Following.as_view(),name="following",),#The test was written
    path('feedfollow/<int:id>/follow/',FeedFollow.as_view(),name="FeedFollow")#The test was written

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class CustomUser(AbstractUser):
    image = models.ImageField(blank=True,null=True,upload_to='userimage/',default='userimage/userimage.jpg',)
    


class MessageFriendModel(models.Model):
    my_user=models.ForeignKey(CustomUser,related_name='my_user',on_delete=models.CASCADE)
    friend_user=models.ForeignKey(CustomUser,related_name='friend_user',on_delete=models.CASCADE)
    date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.my_user.username


class FriendModel(models.Model):
    my_account=models.ForeignKey(CustomUser,related_name='Shexroz',on_delete=models.CASCADE)
    friend_account=models.ForeignKey(CustomUser,related_name='Jasur',on_delete=models.CASCADE)
    vaqt=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.my_account.username

class ChatModel(models.Model):
    my_chat=models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name='my_chat')
    friend_chat = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='friend_chat')
    chat=models.CharField(max_length=350)
    date=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.my_chat.username

users/forms.py
from django import forms
from .models import CustomUser,ChatModel



class ChatFormm(forms.ModelForm):
    chat=forms.CharField(label="", widget=forms.TextInput(
        attrs={
            'class': 'input-chat',
            'placeholder': 'Xabar yozing!',

        }))
    class Meta:
        model=ChatModel
        fields=('chat',)


class UserRegisterFrom(forms.ModelForm):
    username = forms.CharField(label="", widget=forms.TextInput(
        attrs={
        'placeholder':"Enter your username",

        }))
    last_name = forms.CharField(label="", widget=forms.TextInput(
        attrs={
            'placeholder':"Enter your lastname",
        }))
    first_name = forms.CharField(label="", widget=forms.TextInput(
        attrs={
            'placeholder':"Enter your firstname",

        }))
    email = forms.CharField(label="", widget=forms.EmailInput(
        attrs={
            'placeholder':"Enter your email",

        }))
    password = forms.CharField(label="", widget=forms.PasswordInput(
        attrs={
            'class': 'password',
            'placeholder':"Enter your password",

        }))

    class Meta:
        model=CustomUser
        fields=('username','last_name','first_name','email','image','password')

    def save(self, commit=True):
        user=super().save(commit)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return  user

class UserUpdateFrom(forms.ModelForm):
    username = forms.CharField(label="", widget=forms.TextInput(
        attrs={
        'placeholder':"Enter your username",

        }))
    last_name = forms.CharField(label="", widget=forms.TextInput(
        attrs={
            'placeholder':"Enter your lastname",
        }))
    first_name = forms.CharField(label="", widget=forms.TextInput(
        attrs={
            'placeholder':"Enter your firstname",

        }))
    email = forms.CharField(label="", widget=forms.EmailInput(
        attrs={
            'placeholder':"Enter your email",

        }))

    class Meta:
        model=CustomUser
        fields=('username','last_name','first_name','email','image',)

users/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from .models import CustomUser,FriendModel,MessageFriendModel,ChatModel
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import UserRegisterFrom,ChatFormm,UserUpdateFrom
from books.models import FeedModel



# Create your views here.



class RegisterUSer(View):
    def get(self,request):
        form = UserRegisterFrom()
        return render(request,'registers.html',{"form":form,})
    def post(self,request):
        form = UserRegisterFrom(data=request.POST,files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect('users:login')
        else:
            return render(request, 'registers.html', {"form": form,})

class LogoutView(LoginRequiredMixin,View):
    def get(self,request):
        print('foydalanuvchi saytdan chiqdi')
        logout(request)

        return  redirect('users:login')




class LoginUser(View):
    def get(self,request):
        form=AuthenticationForm()

        return render(request,'index.html',{"form":form,})
    def post(self,request):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user=form.get_user()
            login(request,user)
            return redirect('books:feed')
        else:
            return render(request, 'index.html', {"form": form})


class UpdateUser(LoginRequiredMixin,View):
    def get(self,request):
        
        form=UserUpdateFrom(instance=request.user)
        return render(request,'updateuser.html',{"form":form})
    def post(self,request):
        form=UserUpdateFrom(instance=request.user,data=request.POST,files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect('users:userprofile')
        else:
            return render(request,'updateuser.html',{"form":form})
















class FriendChat(LoginRequiredMixin,View):
    def get(self,request):
        sh=request.user
        new1 = ChatModel.objects.filter(my_chat=sh).all()
        new2 = ChatModel.objects.filter(friend_chat=sh).all()
        cos = list(new1) + list(new2)
        for i in range(0,len(cos)):
            s = 0
            for j in range(i+1,len(cos)):
                if cos[i].friend_chat == cos[j-s].friend_chat and  cos[i].my_chat ==cos[j-s].my_chat:
                    cos.pop(j-s)
                    s+=1

        for i in range(0,len(cos)):
            s=0
            for j in range(i+1,len(cos)):
                if cos[i].my_chat == cos[j-s].friend_chat and  cos[i].friend_chat ==cos[j-s].my_chat :
                    cos.pop(j-s)
                    s+=1
        for i in cos:
            for j in cos:
                if i.date > j.date:
                    i.my_chat, j.my_chat = j.my_chat, i.my_chat
                    i.friend_chat, j.friend_chat = j.friend_chat, i.friend_chat
                    i.date, j.date = j.date, i.date
                    i.chat, j.chat = j.chat, i.chat

        return  render(request,'friendchat.html',{"users":cos})


class FriendProfile(LoginRequiredMixin,View):
    def get(self,request,id):
        user = CustomUser.objects.get(id=id)
        friend=FriendModel.objects.filter(my_account=request.user, friend_account=user).exists()
        books=FeedModel.objects.filter(author=user).all()
        sa=books.count()
        follow=FriendModel.objects.filter(my_account=user).count()
        followers=FriendModel.objects.filter(friend_account=user).count()
        return render(request,'friendprofile.html',{"userr":user,"friend":friend,"books":books,"follow":follow,"followers":followers,"sum":sa})

class MyProfile(LoginRequiredMixin,View):
    def get(self,request):

        sh=request.user
        follow = FriendModel.objects.filter(my_account=sh).count()
        folloing = FriendModel.objects.filter(friend_account=sh).count()
        book=FeedModel.objects.filter(author=sh).all()
        sa=book.count()
        return render(request,'userprofile.html',{'userr':sh,"books":book,'sum':sa,"following":folloing,"follow":follow})


class Followers(LoginRequiredMixin,View):
    def get(self,request,id):
        user = CustomUser.objects.get(id=id)
        follow = FriendModel.objects.filter(friend_account=user).all()
        sh = FriendModel.objects.filter(my_account=request.user).values('friend_account').all()
        s=[0]
        for i in sh:
            s.append(i['friend_account'])
        return render(request,'followers.html.',{"follows":follow,'item':s})


class Following(LoginRequiredMixin,View):
    def get(self,request,id):
        user = CustomUser.objects.get(id=id)
        follow = FriendModel.objects.filter(my_account=user).all()
        sh = FriendModel.objects.filter(my_account=request.user).values('friend_account').all()
        s = []
        for i in sh:
            s.append(i['friend_account'])
        return render(request,'following.html',{"follows":follow,'item':s})


class Follow(LoginRequiredMixin,View):
    def get(self,request,id):
        user=CustomUser.objects.get(id=id)
        friend=FriendModel.objects.filter(my_account=request.user, friend_account=user).exists()
        if friend:
            chat=FriendModel.objects.get(my_account=request.user,friend_account=user)
            chat.delete()
            return redirect(reverse("users:user_follow",kwargs={"id": id}))
        else:

            soz = FriendModel.objects.create(my_account=request.user, friend_account=user)
            soz.save()
            got=MessageFriendModel.objects.filter(my_user=request.user, friend_user=user).exists()
            sad = FriendModel.objects.filter(my_account=request.user, friend_account=user).exists()
            if not got and sad:
                chat = MessageFriendModel.objects.create(my_user=request.user, friend_user=user)
                chat.save()
            return redirect(reverse("users:user_follow",kwargs={"id": id}))

class ChatView(LoginRequiredMixin,View):
    def get(self,request,id):
        friend=CustomUser.objects.get(id=id)
        new1=ChatModel.objects.filter(my_chat=request.user,friend_chat=friend).all()
        new2=ChatModel.objects.filter(my_chat=friend,friend_chat=request.user)
        cos=list(new1)+list(new2)
        for i in cos:
            for j in cos:
                if i.date < j.date:
                    i.my_chat, j.my_chat = j.my_chat, i.my_chat
                    i.friend_chat, j.friend_chat = j.friend_chat, i.friend_chat
                    i.date, j.date = j.date, i.date
                    i.chat, j.chat = j.chat, i.chat

        form=ChatFormm()
        return render(request,'mychat.html',{"form":form,'cos':cos,"friend":friend})
    def post(self,request,id):
        form = ChatFormm(data=request.POST)
        frined=CustomUser.objects.get(id=id)
        if form.is_valid():
            chat=request.POST.get('chat')
            sh=ChatModel(my_chat=request.user,friend_chat=frined,chat=chat)
            sh.save()
            return redirect(reverse('users:chat',kwargs={"id":id}))

class FeedFollow(LoginRequiredMixin,View):
    def get(self,request,id):
        user=CustomUser.objects.get(id=id)
        friend=FriendModel.objects.filter(my_account=request.user, friend_account=user).exists()
        if friend:
            chat=FriendModel.objects.get(my_account=request.user,friend_account=user)
            chat.delete()
            return redirect(reverse("books:feed"))
        else:

            soz = FriendModel.objects.create(my_account=request.user, friend_account=user)
            soz.save()
            got=MessageFriendModel.objects.filter(my_user=request.user, friend_user=user).exists()
            sad = FriendModel.objects.filter(my_account=request.user, friend_account=user).exists()
            if not got and sad:
                chat = MessageFriendModel.objects.create(my_user=request.user, friend_user=user)
                chat.save()
            return redirect(reverse("books:feed"))

users/templates/accounts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Userss</h1>
{% for user in users %}
    {% if user != request.user %}
    <img src="{{ user.image.url }}" style="width: 50px;height: 50px; border-radius: 100%;display: inline-block">
    <h1 style="display: inline-block"><a href="{% url "users:user_follow" user.id %}">{{ user.username }}</a> </h1>
    <br>
    {% endif %}
{% endfor %}
</body>
</html>

users/templates/followers.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Responsive Profile Cards | CodingLab</title>
    <link rel="stylesheet" href="{% static 'css/following.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

   <style>
    .fre{
      font-size: 1.2rem;
      position: relative;
      top:1rem;
      color: #ffffff;
    }
    .sa{
      margin-bottom: 1rem;
    }
   </style>
  </head>
              <!-- Creating By CodingLab -->
  <body><div class="fre"><h1>Followers</h1></div>
    <div class="container">
    {% if follows %}
        {% for follow in follows %}
      <div class="box sa">
      <div class="image">
          <img src="{{ follow.my_account.image.url}}">
        </div>
        <div class="name_job">{{ follow.my_account.username}}</div>
        <div class="rating">
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="far fa-star"></i>
          <i class="far fa-star"></i>
          <i class="far fa-star"></i>
        </div>
        <p> Lorem ipsum dolor sitamet, stphen hawkin so adipisicing elit. Ratione disuja doloremque reiciendi nemo.</p>
        <div class="btns">
            <button style="background-color: #8e44ad"><a href="{% url "users:follow" follow.my_account.id  %}" style="text-decoration: none; color: #fff">{% if follow.my_account.id in item %}Unfollow{% else %}Follow{% endif %}</a></button>
          <button>{% if follow.my_account != request.user %}<a href="{% url "users:chat" follow.my_account.id %}" style="text-decoration: none; color: #ffffff">Message</a>{% else %} Message {% endif %}</button>
        </div>
      </div>
      {% endfor %}
    {% else %}
      <div class="box sa">
        <div class="image">
          <img src="img3.jpeg" alt="">
        </div>
        <div class="name_job">No User</div>
          <div class="rating">
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="far fa-star"></i>
        </div>
        <p> Lorem ipsum dolor sitamet, stphen hawkin so adipisicing elit. Ratione disuja doloremque reiciendi nemo.</p>
        <div class="btns">
          <button>Read More</button>
          <button>Message </button>
        </div>
      </div>{% endif %}
    </div>
      </body>
</html>

users/templates/friendprofile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MyProfile</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
    <a href="{% url 'books:feed'%}" style="text-decoration: none; font-size: 1.8rem;color: blanchedalmond;z-index: 22;"><i class="bi bi-box-arrow-left" style="font-size: 2rem; color: white;"></i>Exit</a>
    <div class="wrapper">
		<div class="profile-card js-profile-card">
			<div class="profile-card__img">
				<img src="{{ userr.image.url }}" alt="profile">
			</div>
			<div class="profile-card__cnt js-profile-cnt">
				<div class="profile-card__name">{{ userr.username}}  </div>
				<div class="profile-card__txt">{{ userr.first_name }}  <strong>{{ userr.last_name }}</strong></div>
				<div class="profile-card-loc">
{#					<span class="profile-card-loc__icon">#}
{#						<img src="img/2.jpg" width="30px" height="30px">#}
{##}
{#					</span>#}
					<span class="profile-card-loc__txt">Samarqand,Uzbekistan</span>
				</div>
				<div class="profile-card-inf">
					<div class="profile-card-inf__item">
						<div class="profile-card-inf__title">{{ followers }}</div>
                        <div class="profile-card-inf__txt"><a href="{% url "users:followers" userr.id %}" style="text-decoration: none;color: #324e63">Followers</a></div>

					</div>

					<div class="profile-card-inf__item">
						<div class="profile-card-inf__title">{{ follow }}</div>
						<div class="profile-card-inf__txt"><a href="{% url "users:following" userr.id %}" style="text-decoration: none;color: #324e63">Following</a> </div>

					</div>

					<div class="profile-card-inf__item">
						<div class="profile-card-inf__title">{{ sum }}</div>
						<div class="profile-card-inf__txt">Books</div>

					</div>



				</div>

				<div class="profile-card-social">
					<a href="#" class="profile-card-social__item facebook">
						<span class="icon-font">
							<i class="fa fa-facebook icon"></i>
						</span>
					</a>

					<a href="#" class="profile-card-social__item twitter">
						<span class="icon-font">
							<i class="fa fa-twitter icon"></i>
						</span>
					</a>

					<a href="#" class="profile-card-social__item instagram">
						<span class="icon-font">
							<i class="fa fa-instagram icon"></i>
						</span>
					</a>

					<a href="#" class="profile-card-social__item behance">
						<span class="icon-font">
							<i class="fa fa-google icon"></i>
						</span>
					</a>




				</div>

				<div class="profile-card-ctr">
					<button class="profile-card__button button--blue js-message-btn"><a href="{% url "users:chat" userr.id %}" style="text-decoration: none; color: #fff">Message</a> </button>
					<button class="profile-card__button button--orange"><a href="{% url "users:follow" userr.id  %}" style="text-decoration: none; color: #fff">{% if friend %}Unfollow{% else %} Follow{% endif %}</a></button>
				</div>
			</div>
			
			
		</div>

	</div>

    <div class="card-general">
          <div class="container">
              {% for book in books %}
        <div class="box">
        <div class="image">
            <img src="{{ book.image.url }}">
          </div>
          <div class="name_job" style="background-color:rgb(44, 41, 41); color: #fff;">{{ book.name }}</div>
         
          <p >{{ book.title }}  </p>
          <div class="btns">
            <a download="{{ book.file }}" href="{{ book.file.url }}"><button style="background-color: #8e44ad;">Downlaod</button></a>
            <a href="{% url 'books:detail' book.id %}"><button style="background-color: #8e44ad;">Comment</button></a>
          </div>
        </div>{% endfor %}


        </div>
      </div>
    </div>
  
</body>
</html>

users/templates/userprofile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MyProfile</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
    <a href="{% url 'books:feed'%}" style="text-decoration: none; font-size: 1.8rem;color: blanchedalmond;z-index: 22;"><i class="bi bi-box-arrow-left" style="font-size: 2rem; color: white;"></i>Exit</a>
    <div class="wrapper">
		
		<div class="profile-card js-profile-card">
			<div class="profile-card__img">
				<img src="{{ userr.image.url }}" alt="profile">
			</div>
			<div class="profile-card__cnt js-profile-cnt">
				<div class="profile-card__name">{{ userr.username}}</div>
				<div class="profile-card__txt">{{ userr.first_name }}  <strong>{{ userr.last_name }}</strong></div>
				<div class="profile-card-loc">
					<span class="profile-card-loc__icon">
					<img src="img/2.jpg" width="30px" height="30px">

				</span>
					<span class="profile-card-loc__txt">Samarqand,Uzbekistan</span>
				</div>
				<div class="profile-card-inf">
					<div class="profile-card-inf__item">
						<div class="profile-card-inf__title">{{ following }}</div>
                        <div class="profile-card-inf__txt"><a href="{% url "users:followers" userr.id %}" style="text-decoration: none;color: #324e63">Followers</a></div>

					</div>

					<div class="profile-card-inf__item">
						<div class="profile-card-inf__title">{{ follow }}</div>
						<div class="profile-card-inf__txt"><a href="{% url "users:following" userr.id %}" style="text-decoration: none;color: #324e63">Following</a> </div>

					</div>

					<div class="profile-card-inf__item">
						<div class="profile-card-inf__title">{{ sum }}</div>
						<div class="profile-card-inf__txt">Books</div>

					</div>



				</div>

				<div class="profile-card-social">
					<a href="#" class="profile-card-social__item facebook">
						<span class="icon-font">
							<i class="fa fa-facebook icon"></i>
						</span>
					</a>

					<a href="#" class="profile-card-social__item twitter">
						<span class="icon-font">
							<i class="fa fa-twitter icon"></i>
						</span>
					</a>

					<a href="#" class="profile-card-social__item instagram">
						<span class="icon-font">
							<i class="fa fa-instagram icon"></i>
						</span>
					</a>

					<a href="#" class="profile-card-social__item behance">
						<span class="icon-font">
							<i class="fa fa-google icon"></i>
						</span>
					</a>




				</div>

				<div class="profile-card-ctr">
					<button class="profile-card__button button--blue js-message-btn"><a href="{% url "users:updateuser"  %}" style="text-decoration: none; color: #fff"><i class="bi bi-pen-fill" style="font-size: 2rem; color: white;"></i>Edit Profile</a> </button>
					<button class="profile-card__button button--orange"><a href="{% url "books:bookcreate" %}" style="text-decoration: none; color: #fff"><i class="bi bi-book-half" style="font-size: 2rem; color: white;"></i>  Create Book</a></button>
				</div>
			</div>
			
			
		</div>

	</div>

    <div class="card-general">
          <div class="container">
              {% for book in books %}
        <div class="box">
			<p><a href="{% url 'books:bookedit' book.id %}">   <i class="bi bi-pen" style="position: relative;left: 100px; color: black; font-size: 1.5rem;"></i></a>
            <a style="margin-left: 10px;" href="{% url 'books:deletemessage' book.id %}">   <i class="bi bi-trash" style="position: relative;left: 100px;color:black; font-size: 1.5rem;"></i></a></p>
        <div class="image">
            <img src="{{ book.image.url }}">
          </div>
          <div class="name_job" style="color: white;background-color: #212529">{{ book.name }}</div>

          <p>{{ book.title }}Bu zor kitob ekan.KampyuterniBu zorKampyuterniBu zorKampyuterniBu zor  </p>
          <div class="btns">
            <a download="{{ book.file}}" href="{{ book.file.url }}"><button style="background-color: #8e44ad;">Download</button></a>
            <a href="{% url "books:detail" book.id %}"><button style="background-color: #8e44ad;">Comments</button></a>
          </div>
        </div>{% endfor %}


        </div>
      </div>
    </div>
  
</body>
</html>

users/templates/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Users</h1>
{% for user in users %}
    {% if user != request.user %}
        <img src="{{ user.image.url }}" style="display: inline-block; width: 50px; height: 50px; border-radius: 100%">
        <a href="{% url "users:chat" user.id %}">{{ user.username }}</a><br><br>
    {% endif %}
{% endfor %}
</body>
</html>