basic/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('feed/',include('books.urls'))
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404="notfound.views.page_not_found_view"
handler500="notfound.views.handle_server_found"

books/urls.py
from django.urls import path
from .views import  (   
                        FeedBookView,
                        DetailView,
                        LikeView,
                        BookCreateView,
                        BookEditView,
                        BookDeleteView,
                        BookSearch,
                        UserSearch,
                        BookReviewEdit,
                        CommentDelete,
                        CommentDeletes,
                        BookDeleteMessage,
                        FriendReview,
                        BookTop,
                        favouritebook,
                        deletefavouritebook,
                        FavouriteBook
        
)


app_name='books'
urlpatterns=[
    path('',FeedBookView.as_view(),name='feed'),# wrote test
    path('bookserach/',BookSearch.as_view(),name='booksearch'),# wrote test
    path('usersearch/',UserSearch.as_view(),name="usersearch"),# wrote test
    path('bookTop/',BookTop.as_view(),name="Booktop"),
    path('mybookfavourite/',FavouriteBook.as_view(),name="bookfavourite"),
    path('friendreviw/',FriendReview.as_view(),name="friendreview"),
    path('<int:id>/',DetailView.as_view(),name='detail'),# wrote test
    path('like/<int:id>/',LikeView.as_view(),name="like"),# wrote test
    path('bookcreate/',BookCreateView.as_view(),name="bookcreate"),
    path('bookcreate/<int:id>/edit/',BookEditView.as_view(),name="bookedit"),
    path('bookdelete/<int:id>/messge/',BookDeleteMessage.as_view(),name="deletemessage"),# wrote test
    path('bookcreate/<int:id>/delete/',BookDeleteView.as_view(),name="bookdelete"),# wrote test
    path('<int:book_id>/comments/<int:comment_id>/edit/',BookReviewEdit.as_view(),name='commentedit'), # wrote test
    path('<int:book_id>/view/<int:comment_id>',CommentDelete.as_view(),name='commentdelete'),# wrote test
    path('<int:book_id>/delete/<int:comment_id>deletes/',CommentDeletes.as_view(),name='commentdeletes'),# wrote test
    path('favouritebook/<int:id>/',favouritebook.as_view(),name='favourite'),
    path('favouritebook/<int:id>/delete',deletefavouritebook.as_view(),name='deletelikebook'),

]

users/urls.py
from django.urls import path
from .views import ( RegisterUSer,
                     LoginUser,
                     LogoutView,
                     FriendChat,
                     FriendProfile,
                     Follow,
                     ChatView,
                     MyProfile,
                     Followers,
                     Following,
                     UpdateUser,
                     FeedFollow
                     )



app_name='users'
urlpatterns=[
    path('register/',RegisterUSer.as_view(),name='register'),#The test was written
    path('profile/',MyProfile.as_view(),name='userprofile'),#The test was written
    path('profile/updateuserprofile/',UpdateUser.as_view(),name='updateuser'),#The test was written
    path('',LoginUser.as_view(),name='login'),#The test was written
    path('logout/',LogoutView.as_view(),name='logout'),#The test was written
    path('friendchat/',FriendChat.as_view(),name="friendchat",),#The test was written
    path('users/<int:id>/',FriendProfile.as_view(),name="user_follow",),
    path('users/<int:id>/follow/',Follow.as_view(),name="follow",),#The test was written
    path('friendchat/<int:id>/chat/',ChatView.as_view(),name="chat",),#The test was written
    path('users/<int:id>/followers/',Followers.as_view(),name="followers",),#The test was written
    path('users/<int:id>/following/',Following.as_view(),name="following",),#The test was written
    path('feedfollow/<int:id>/follow/',FeedFollow.as_view(),name="FeedFollow")#The test was written

]

books/forms.py
from django import forms
from .models import Comments,FeedModel
class CommentForm(forms.ModelForm):
    comments = forms.CharField(label="", widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'placeholder': 'Comment here!',
            'rows': 4,
            'cols': 50
        }))

    class Meta:
        model = Comments
        fields = ['comments']

class BookCreateForm(forms.ModelForm):
    name = forms.CharField(label="", widget=forms.TextInput(
        attrs={
            'placeholder': 'Enter book name',
        }))
    title = forms.CharField(label="", widget=forms.Textarea(
        attrs={
            "rows":6,
            'placeholder': 'You descreption your book',
        }))
    image = forms.ImageField(label="Book image choose", widget=forms.FileInput(
        attrs={

        }))
    file = forms.FileField(label="Book file choose ", widget=forms.FileInput(
        attrs={
        }))

    class Meta:
        model = FeedModel
        fields = ['name','title','image','file']

class ExampleForm(forms.Form):
    CHOISES=[
        (1,''),
    ]
    num1=forms.ChoiceField(required=False,choices=CHOISES,widget=forms.RadioSelect(attrs={
        # 'class':'num',
        # 'value':1,
    }))
    num2=forms.ChoiceField(required=False,choices=CHOISES,widget=forms.RadioSelect(attrs={
        # 'class':'num',
        # 'value':1,
    }))
    num3=forms.ChoiceField(required=False,choices=CHOISES,widget=forms.RadioSelect(attrs={
        # 'class':'num',
        # 'value':1,
    }))
    num4=forms.ChoiceField(required=False,choices=CHOISES,widget=forms.RadioSelect(attrs={
        # 'class':'num',
        # 'value':1,
    }))
    num5=forms.ChoiceField(required=False,choices=CHOISES,widget=forms.RadioSelect(attrs={
        # 'class':'num',
        # 'value':1,
    }))
    comments = forms.CharField(label="", widget=forms.Textarea(
        attrs={
            
        }))
class ExampleForms(forms.ModelForm):
    CHOISES=[
        (1,None),
    ]
    num1=forms.ChoiceField(required=False,choices=CHOISES,widget=forms.RadioSelect(attrs={
        # 'class':'num',
        # 'value':1,
    }))
    num2=forms.ChoiceField(required=False,choices=CHOISES,widget=forms.RadioSelect(attrs={
        # 'class':'num',
        # 'value':1,
    }))
    num3=forms.ChoiceField(required=False,choices=CHOISES,widget=forms.RadioSelect(attrs={
        # 'class':'num',
        # 'value':1,
    }))
    num4=forms.ChoiceField(required=False,choices=CHOISES,widget=forms.RadioSelect(attrs={
        # 'class':'num',
        # 'value':1,
    }))
    num5=forms.ChoiceField(required=False,choices=CHOISES,widget=forms.RadioSelect(attrs={
        # 'class':'num',
        # 'value':1,
    }))
    comments = forms.CharField(label="", widget=forms.Textarea(
        attrs={
            
        }))
    class Meta:
        model = Comments
        fields = ['comments']

books/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View
from .forms import CommentForm,BookCreateForm,ExampleForm
from .models import FeedModel,Comments,LikeBook
from users.models import CustomUser,FriendModel
from django.core.paginator import Paginator
from users.models import MessageFriendModel


# Create your views here.


class FeedBookView(LoginRequiredMixin,View):
    def get(self,request):
        #user follow message
        new=MessageFriendModel.objects.filter(friend_user=request.user).all().order_by("-id")
        suma=new.count()
        
        for i in new:
            print(i.my_user)
        #Book get
        friend=FriendModel.objects.filter(my_account=request.user).all()
        if friend:
            book=list()
            for i in friend:
                book+=list(FeedModel.objects.filter(author=i.friend_account).all())
            for i in range(0,len(book)):
                for j in range(i+1,len(book)):
                    if book[i].date <= book[j].date:
                        book[i],book[j]=book[j],book[i]

                    elif book[i].date == book[j].date:
                        if book[i].like.count() <= book[j].like.count():
                            book[i], book[j] = book[j], book[i]
                        else:
                            book[i]=book[i]
                            book[j]=book[j]
                    else:
                        book[i] = book[i]
                        book[j] = book[j]
        
        else:
            book=list(FeedModel.objects.all())
            for i in range(0,len(book)):
                for j in range(i+1,len(book)):
                    if book[i].like.count() <= book[j].like.count():
                        book[i],book[j]=book[j],book[i]
                    elif book[i].like.count() == book[j].like.count():
                        if book[i].date <= book[j].date:
                            book[i],book[j]=book[j],book[i]


                        else:
                            book[i]=book[i]
                            book[j]=book[j]
                    else:
                        book[i] = book[i]
                        book[j] = book[j]
        page=request.GET.get('page',1)
        pagination=Paginator(book,6)
        page_obg=pagination.get_page(page)

        #user top
        user=list(CustomUser.objects.all())
        n=0
        for i in range(len(user)):
            if  FriendModel.objects.filter(my_account=request.user,friend_account=user[i-n]).exists() or request.user==user[i-n]:
                user.pop(i-n)
                
                n+=1
     
        
       
        return render(request,'feed.html',{"page_obg":page_obg,"new":new,"n":suma,"userfollow":user})
class BookTop(LoginRequiredMixin,View):
    def get(self,request):
        book=list(FeedModel.objects.all())
        for i in range(0,len(book)):
            for j in range(i+1,len(book)):
                if book[i].like.count() <= book[j].like.count():
                    book[i],book[j]=book[j],book[i]
                elif book[i].like.count() == book[j].like.count():
                    if book[i].date <= book[j].date:
                        book[i],book[j]=book[j],book[i]


                    else:
                        book[i]=book[i]
                        book[j]=book[j]
                else:
                    book[i] = book[i]
                    book[j] = book[j]
        page=request.GET.get('page',1)
        pagination=Paginator(book,6)
        page_obg=pagination.get_page(page)
        return render(request,'best_Book.html',{"page_obg":page_obg,})
class DetailView(LoginRequiredMixin,View):
    def get(self,request,id):
        book=FeedModel.objects.get(id=id)
        sights=book.sight.all()
        user=request.user
        if user in sights:
            print(user.username)
        else:
            book.sight.add(user)
        forms=ExampleForm(request.POST or None)
        comments = Comments.objects.filter(book=book).order_by("-id")
        return render(request,'book_detile.html',{"book":book,"forms":forms,"commentss":comments})
    def post(self,request,id):
        forms=ExampleForm(request.POST or None)
        book=FeedModel.objects.get(id=id)
        if forms.is_valid():
            num1=request.POST.get('num1' or '')
            num2=request.POST.get('num2' or '')
            num3=request.POST.get('num3' or '')
            num4=request.POST.get('num4' or '')
            num5=request.POST.get('num5' or '')
            comments=request.POST.get('comments')
            num=[num1,num2,num3,num4,num5]
           
            print(num)
            
            
            s=5
            for i in range(0,len(num)):
                if num[i]=='' or num[i]==None :
                    s-=1
                else:
                    
                    break
            
            comment=Comments.objects.create(user=request.user,book=book,comments=comments,star=s)
            comment.save()
            return redirect('/feed/{}'.format(id))
        else:
            comment_from = CommentForm()
            book = FeedModel.objects.get(id=id)
            return render(request, 'detail.html', {"book": book, "form_comment": comment_from})

class LikeView(LoginRequiredMixin,View):
    def get(self,request,id):
        book=FeedModel.objects.get(id=id)
        likes=book.like.all()
        user=request.user
        if user in likes:
            book.like.remove(user)
        else:
            book.like.add(user)
        return redirect('books:feed')

class BookCreateView(LoginRequiredMixin,View):
    def get(self,request):
        form=BookCreateForm()
        return render(request,'bookcreates.html',{"form":form})
    def post(self,request):
        form = BookCreateForm(data=request.POST,files=request.FILES)
        if form.is_valid():
            user=request.user
            name=request.POST.get('name')
            title=request.POST.get('title')
            image=request.FILES.get('image')
            file=request.FILES.get('file')
            sa=FeedModel.objects.create(author=user,title=title,image=image,file=file,name=name,)
            sa.save()
            return redirect('users:userprofile')
        else:
            return render(request, 'bookcreates.html', {"form": form})

class BookEditView(LoginRequiredMixin,View):
    def get(self,request,id):
        book=FeedModel.objects.get(id=id)
        form=BookCreateForm(instance=book)
        return render(request,'bookedits.html',{"form":form})
    def post(self,request,id):
        book = FeedModel.objects.get(id=id)
        form=BookCreateForm(instance=book,data=request.POST,files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect('users:userprofile')
        else:
            return render(request,'bookedits.html',{"form":form})

class BookDeleteMessage(View):
    def get(self,request,id):
        sh=request.user
        book=FeedModel.objects.get(id=id)
        return render(request,'bookdelete.html',{"book":book,'user':sh})
class BookDeleteView(LoginRequiredMixin,View):
    def get(self,request,id):
        book=FeedModel.objects.get(id=id)
        book.delete()
        return redirect('users:userprofile')

class BookSearch(View):
    def get(self,request):
        name=request.GET.get('q','')
        if name!= '':
            # Foydalanuvchiga izlatgan kitobi boyicha eng like kop va vaqtliroq chiqqan kitoblar ko'rastiladi.
            books=FeedModel.objects.filter(name__icontains=name).all()
            book=list(books)
            for i in range(0,len(book)):
                for j in range(i+1,len(book)):
                    if book[i].date <= book[j].date:
                        book[i],book[j]=book[j],book[i]

                    elif book[i].date == book[j].date:
                        if book[i].like.count() <= book[j].like.count():
                            book[i], book[j] = book[j], book[i]
                        else:
                            book[i]=book[i]
                            book[j]=book[j]
                    else:
                        book[i] = book[i]
                        book[j] = book[j]
        else:
            # Agar foydalanuvchi kitob izlatgan bolsa unga eng kop like bor va vaqtliroq chiqqan kitoblar korsatiladi
            #  kitoblarni korsatiladi.
            books=FeedModel.objects.all()[:5]
            book=list(books)
            for i in range(0,len(book)):
                for j in range(i+1,len(book)):
                    if  book[i].like.count() <= book[j].like.count():
                        book[i],book[j]=book[j],book[i]

                    elif book[i].like.count() == book[j].like.count():
                        if book[i].date <= book[j].date:
                            book[i], book[j] = book[j], book[i]
                        else:
                            book[i]=book[i]
                            book[j]=book[j]
                    else:
                        book[i] = book[i]
                        book[j] = book[j]
        return render(request,'booksearch.html',{'books':book})


class UserSearch(LoginRequiredMixin,View):
    def get(self,request):
        uss=request.GET.get('q' or None)
        print(uss)
        if uss !='' and uss != None:
            users=CustomUser.objects.filter(username__icontains=uss).all()
        else:
            books=FeedModel.objects.all()
            book=list(books)
            for i in range(0,len(book)):
                for j in range(i+1,len(book)):
                    if  book[i].like.count() <= book[j].like.count():
                        book[i],book[j]=book[j],book[i]

                    elif book[i].like.count() == book[j].like.count():
                        if book[i].date <= book[j].date:
                            book[i], book[j] = book[j], book[i]
                        else:

books/templates/commentdelete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/commentedit.css'%}">
    <link rel="stylesheet" href="icons/css/font-awesome.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<style>
  h1{
    font-size: 1.2rem;
  }
</style>
</head>
<body>
    <header>
      
        <div class="head-container">
          <form>
       <p>{{comment.comments}}</p> <h1 style="color:dimgrey">Are you going to delete this review?</h1>
          </form>
             

             <a href="{% url "books:detail" book.id %}" style="background-color: rgb(247, 27, 27); border: 1px solid red;" class="btn btn-primary btn-lg active sa" role="button" aria-pressed="true">No</a>
             <a href="{% url "books:commentdeletes" book.id comment.id %}" style="background-color: rgba(29, 192, 14, 0.952); border: 1px solid green;" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Yes</a>
        </div>
    </header>
</body>
</html>

books/templates/friendcommentview.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- fontawesome -->
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
      integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <!-- bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU"
      crossorigin="anonymous"
    />
    <!-- main style -->
    <link rel="stylesheet" href="{% static 'css/feed.css' %}" />
    <title>Flexbook</title>
  </head>
  <body class="bg-gray postion-relative">
    <!-- ================= Appbar ================= -->
   
    <!-- =============== New Chat Mobile =============== -->
    
    <!-- ================= Chat Modal Mobile ================= -->
    <!-- chat 1 -->
    

    <!-- ================= Main ================= -->
    <div class="container-fluid">
        
      <div class="row justify-content-evenly">
        
        <!-- ================= Sidebar ================= -->
        <div class="col-12 col-lg-3">
            <a href="{% url "books:feed" %}" style="text-decoration: none; font-size: 1.8rem;color: blue;position:fixed;"><i class="bi bi-box-arrow-left" style="font-size: 2rem; color: blue;"></i>Exit</a>
        </div>
        <!-- ================= Timeline ================= -->
        <div class="col-12 col-lg-6 pb-5">
          <div
            class="d-flex flex-column justify-content-center w-100 mx-auto"
            style="padding-top: 56px; max-width: 680px"
          >
            <!-- stories -->

            <!-- create post -->

            <!-- create room -->

            <!-- posts -->
            <!-- p 1 -->

            <!-- p 2 -->
            {% for comment in page_obg.object_list %}
            <div class="bg-white p-4 rounded shadow mt-3">
              <!-- author -->
              <div class="d-flex justify-content-between">
                <!-- avatar -->
                <div class="d-flex">
                  <img
                    src="{{ comment.user.image.url }}"
                    alt="avatar"
                    class="rounded-circle me-2"
                    style="width: 38px; height: 38px; object-fit: cover"
                  />
                  <div>
                    <p class="m-0 fw-bold"><a href="{% url "users:user_follow" comment.user.id %}" style="text-decoration: none;">{{ comment.user.username }}</p>
                    <span class="text-muted fs-7">{{ comment.time | date:"H:i d M" }}</span>
                    {% if comment.star == 1%}
                    <a><i style="color: yellow;" class="fa fa-star"></i></a>
                    <a><i class="fa fa-star"></i></a>
                    <a><i class="fa fa-star"></i></a>
                    <a><i class="fa fa-star"></i></a>
                    <a><i class="fa fa-star"></i></a>
                    {%endif%}
                    {% if comment.star == 2%}
                    <a><i style="color: yellow;" class="fa fa-star"></i></a>
                    <a><i style="color: yellow;" class="fa fa-star"></i></a>
                    <a><i class="fa fa-star"></i></a>
                    <a><i class="fa fa-star"></i></a>
                    <a><i class="fa fa-star"></i></a>
                    {%endif%}
                    {% if comment.star == 3%}
                    <a><i style="color: yellow;" class="fa fa-star"></i></a>
                    <a><i style="color: yellow;" class="fa fa-star"></i></a>
                    <a><i style="color: yellow;" class="fa fa-star"></i></a>
                    <a><i class="fa fa-star"></i></a>
                    <a><i class="fa fa-star"></i></a>
                    {%endif%}
                    {% if comment.star == 4%}
                    <a><i style="color: yellow;" class="fa fa-star"></i></a>
                    <a><i style="color: yellow;" class="fa fa-star"></i></a>
                    <a><i style="color: yellow;" class="fa fa-star"></i></a>
                    <a><i style="color: yellow;" class="fa fa-star"></i></a>
                    <a><i class="fa fa-star"></i></a>
                    {%endif%}
                    {% if comment.star == 5%}
                    <a><i style="color: yellow;" class="fa fa-star"></i></a>
                    <a><i style="color: yellow;" class="fa fa-star"></i></a>
                    <a><i style="color: yellow;" class="fa fa-star"></i></a>
                    <a><i style="color: yellow;" class="fa fa-star"></i></a>
                    <a><i style="color: yellow;" class="fa fa-star"></i></a>
                    {%endif%}
                    {% if request.user == comment.user %}
                    <a href="{% url "books:commentedit" book.id comment.id %}">   <i class="bi bi-pen" style="position: relative;left: 20px;"></i></a>
                    <a href="{% url "books:commentdelete" book.id comment.id %}">   <i class="bi bi-trash" style="position: relative;left: 20px;"></i></a>
                    {% endif %}
                  </div>
                </div>
              </div>
              <!-- post content -->
              <div class="mt-3">
                <!-- content -->
                <div>
                  <p>
                   {{ comment.comments }}
                  </p>
                  <h1 style="font-size: 1.2em; text-align: center; color: #212529;">{{comment.book.name}}</h1>
                  <img
                    src="{{comment.book.image.url}}"
                    alt="post image"
                    class="img-fluid rounded"
                    style="width: 100%; height:20em;"
                  />
                </div>
                <!-- likes & comments -->
                <div class="post__comment mt-3 position-relative"> 
                  <!-- likes -->
                  <div
                    class="
                      d-flex
                      align-items-center
                      top-0
                      start-0
                      position-absolute
                    "
                    style="height: 50px; z-index: 5"
                  >
                    
                    
                  </div>
                  <!-- comments start-->
                  <div class="accordion" id="accordionExample">
                    <div class="accordion-item border-0">
                      <!-- comment collapse -->
                    
                      
                      <!-- comment & like bar -->
                      
                      <!-- comment expand -->
                      
                    </div>
                  </div>
                  <!-- end -->
                </div>
              </div>
            </div>{% endfor %}
   
            <nav aria-label="Page navigation example" style="margin:auto;position: relative; top: 20px;">
                <ul class="pagination">
                    {% if page_obg.has_previous %}
                  <li class="page-item"><a class="page-link" href="{% url 'books:friendreview' %}?page={{ page_obg.previous_page_number }}">Previous</a></li>
                  {% endif%}
                  <li class="page-item"><a class="page-link" href="#">{{page_obg.number}}</a></li>
                 
                  {% if page_obg.has_next %}
                  <li class="page-item"><a class="page-link" href="{% url 'books:friendreview' %}?page={{ page_obg.next_page_number }}"">Next</a></li>
                  {% endif%}
                </ul>
              </nav>
          </div>
        </div>
        <!-- ================= Chatbar ================= -->
        <div class="col-12 col-lg-3">

      </div>
    </div>

    <!-- ================= Chat Icon ================= -->
    <div
      class="fixed-bottom right-100 p-3"
      style="z-index: 6; left: initial"
      type="button"
      data-bs-toggle="modal"
      data-bs-target="#newChat"
    >

    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
      crossorigin="anonymous"
    ></script>
   
  </body>
</html>

books/templates/myfavouritebook.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My favourite books</title>
    <link rel="stylesheet" href="{% static 'css/myfavouritebook.css' %}">
    <link rel="stylesheet" href="icons/css/font-awesome.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>
<body>
    
    
<h1 style="text-align: center;color: white; font-size: 2rem;">My Favourite Books</h1>
    <div class="card-general">
          <div class="container">
        {%  if books %}
        {% for book in books%}
        <div class="box">
          <p>
            <a style="margin-left: 10px;" href="{% url 'books:deletelikebook' book.booklike.id %}">   <i class="bi bi-trash" style="position: relative;left: 100px;color:black; font-size: 1.5rem;"></i></a></p>
        <div class="image">
            <img src="{{book.booklike.image.url}}">
          </div>
          <div class="name_job">{{book.booklike.name}}</div>
          <!-- <div class="rating">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="far fa-star"></i>
            <i class="far fa-star"></i>
            <i class="far fa-star"></i>
          </div> -->
          
          <p>{{book.booklike.title}} Lorem ipsum dolor sitamet, stphen hawkin so adipisicing elit. Ratione disuja doloremque reiciendi nemo. </p>
          <div class="btns">
          <a download="{{ book.booklike.file}}" href="{{ book.booklike.file.url }}"><button style="background-color: #8e44ad;">Dowlounds </button></a>
          <a href="{% url "books:detail" book.booklike.id %}"><button style="background-color: #8e44ad;">Comments</button></a>
          </div>
        </div>
        
        {% endfor %}
        {% else %}
        <h1 style="text-align: center;color: white; font-size: 2rem;">You Favourite Books is no</h1>
        {% endif %}
        
        </div>
      </div>
    </div>
  
</body>
</html>