basic/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('feed/',include('books.urls'))
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404="notfound.views.page_not_found_view"
handler500="notfound.views.handle_server_found"

books/urls.py
from django.urls import path
from .views import  (   
                        FeedBookView,
                        DetailView,
                        LikeView,
                        BookCreateView,
                        BookEditView,
                        BookDeleteView,
                        BookSearch,
                        UserSearch,
                        BookReviewEdit,
                        CommentDelete,
                        CommentDeletes,
                        BookDeleteMessage,
                        FriendReview,
                        BookTop,
                        favouritebook,
                        deletefavouritebook,
                        FavouriteBook
        
)


app_name='books'
urlpatterns=[
    path('',FeedBookView.as_view(),name='feed'),# wrote test
    path('bookserach/',BookSearch.as_view(),name='booksearch'),# wrote test
    path('usersearch/',UserSearch.as_view(),name="usersearch"),# wrote test
    path('bookTop/',BookTop.as_view(),name="Booktop"),
    path('mybookfavourite/',FavouriteBook.as_view(),name="bookfavourite"),
    path('friendreviw/',FriendReview.as_view(),name="friendreview"),
    path('<int:id>/',DetailView.as_view(),name='detail'),# wrote test
    path('like/<int:id>/',LikeView.as_view(),name="like"),# wrote test
    path('bookcreate/',BookCreateView.as_view(),name="bookcreate"),
    path('bookcreate/<int:id>/edit/',BookEditView.as_view(),name="bookedit"),
    path('bookdelete/<int:id>/messge/',BookDeleteMessage.as_view(),name="deletemessage"),# wrote test
    path('bookcreate/<int:id>/delete/',BookDeleteView.as_view(),name="bookdelete"),# wrote test
    path('<int:book_id>/comments/<int:comment_id>/edit/',BookReviewEdit.as_view(),name='commentedit'), # wrote test
    path('<int:book_id>/view/<int:comment_id>',CommentDelete.as_view(),name='commentdelete'),# wrote test
    path('<int:book_id>/delete/<int:comment_id>deletes/',CommentDeletes.as_view(),name='commentdeletes'),# wrote test
    path('favouritebook/<int:id>/',favouritebook.as_view(),name='favourite'),
    path('favouritebook/<int:id>/delete',deletefavouritebook.as_view(),name='deletelikebook'),

]

templates/eror.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>PAge Not found</h1>
</body>
</html>

templates/notemplate.html
{% load static %}
<!DOCTYPE html>
<!-- Created By CodingNepal -->
<html lang="en" dir="ltr">
   <head>
      <meta charset="utf-8">
      <title>404 Error Page | CodingNepal</title>
      <link rel="stylesheet" href="{% static 'css/eror.css' %}">
      <style>
         @import url('https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap');
*{
  margin: 0;
  padding: 0;
  outline: none;
  box-sizing: border-box;
  font-family: 'Poppins', sans-serif;
}
body{
  height: 100vh;
  background: -webkit-repeating-linear-gradient(-45deg, #71b7e6, #69a6ce, #b98acc, #ee8176, #b98acc, #69a6ce, #9b59b6);
  background-size: 400%;
}
#error-page{
  position: absolute;
  top: 10%;
  left: 15%;
  right: 15%;
  bottom: 10%;
  display: flex;
  align-items: center;
  justify-content: center;
  background: #fff;
  box-shadow: 0px 5px 10px rgba(0,0,0,0.1);
}
#error-page .content{
  max-width: 600px;
  text-align: center;
}
.content h2.header{
  font-size: 18vw;
  line-height: 1em;
  position: relative;
}
.content h2.header:after{
  position: absolute;
  content: attr(data-text);
  top: 0;
  left: 0;
  right: 0;
  background: -webkit-repeating-linear-gradient(-45deg, #71b7e6, #69a6ce, #b98acc, #ee8176, #b98acc, #69a6ce, #9b59b6);
  background-size: 400%;
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  text-shadow: 1px 1px 2px rgba(255,255,255,0.25);
  animation: animate 10s ease-in-out infinite;
}
@keyframes animate {
  0%{
    background-position: 0 0;
  }
  25%{
    background-position: 100% 0;
  }
  50%{
    background-position: 100% 100%;
  }
  75%{
    background-position: 0% 100%;
  }
  100%{
    background-position: 0% 0%;
  }
}
.content h4{
  font-size: 1.5em;
  margin-bottom: 20px;
  text-transform: uppercase;
  color: #000;
  font-size: 2em;
  max-width: 600px;
  position: relative;
}
.content h4:after{
  position: absolute;
  content: attr(data-text);
  top: 0;
  left: 0;
  right: 0;
  text-shadow: 1px 1px 2px rgba(255,255,255,0.4);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}
.content p{
  font-size: 1.2em;
  color: #0d0d0d;
}
.content .btns{
  margin: 25px 0;
  display: inline-flex;
}
.content .btns a{
  display: inline-block;
  margin: 0 10px;
  text-decoration: none;
  border: 2px solid #69a6ce;
  color: #69a6ce;
  font-weight: 500;
  padding: 10px 25px;
  border-radius: 25px;
  text-transform: uppercase;
  transition: all 0.3s ease;
}
.content .btns a:hover{
  background: #69a6ce;
  color: #fff;
}
      </style>
   </head>
   <body>
      <div id="error-page">
         <div class="content">
            <h2 class="header" data-text="404">
               404
            </h2>
            <h4 data-text="Opps! Page not found">
               Opps! Page not found
            </h4>
            <p>
               Sorry, the page you're looking for doesn't exist. If you think something is broken, report a problem.
            </p>
            <div class="btns">
               <a href="{% url 'books:feed' %}">return home</a>
               <a href="{% url 'books:feed' %}">report problem</a>
            </div>
         </div>
      </div>
   </body>
</html>